version: '3.8'

services:
  web:
    build: .
    command: >
      sh -c "python manage.py migrate &&
             gunicorn consultas_api.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Aqui a definição do volume está correta
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: consultas_db
      POSTGRES_USER: consultas
      POSTGRES_PASSWORD: consultas
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Volume correto
    ports:
      - "5432:5432"

volumes:
  postgres_data: {}  # Volumes agora são mapeados corretamente

