version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    env_file:
      - .env


  db:
    image: postgres:15
    environment:
      POSTGRES_DB: consultas_db
      POSTGRES_USER: consultas
      POSTGRES_PASSWORD: consultas
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
