# Generated by Django 5.2 on 2025-04-15 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='status_pagamento',
            field=models.CharField(default='PENDENTE', max_length=50),
        ),
        migrations.AddField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RenameModel(
            old_name='ProfissionalSaude',
            new_name='Profissional',
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('mock_id', models.CharField(max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.consulta')),
                ('profissional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consultas.profissional')),
            ],
        ),
    ]
